# For more information, please refer to https://aka.ms/vscode-docker-python
FROM nvidia/cuda:11.1-base-ubuntu20.04

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# Install pip requirements

RUN apt-get update && apt-get install -y python3 python3-dev python3-pip

#RUN python --version
#RUN pip --version
WORKDIR /app
ADD ./RL-wrapper-gym/requirements.txt ./requirements_RL-wrapper-gym.txt
ADD ./gym-jsbsim-simple/requirements.txt ./requirements_gym-jsbsim-simple.txt
ADD ./landing-the-eagle/requirements.txt ./requirements_landing-the-eagle.txt

RUN python3 -m pip install -r ./requirements_RL-wrapper-gym.txt
RUN python3 -m pip install -r ./requirements_gym-jsbsim-simple.txt
RUN python3 -m pip install -r ./requirements_landing-the-eagle.txt
