# For more information, please refer to https://aka.ms/vscode-docker-python
FROM stablebaselines/rl-baselines3-zoo

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# Install pip requirements

# RUN apt-get update && apt-get install -y python3 python3-dev python3-pip

RUN python --version
RUN pip --version
WORKDIR ${CODE_DIR}
ADD ./requirements.txt ./requirements.txt

RUN python3 -m pip install -r ./requirements.txt
#RUN python3 -m pip install -r ./requirements_jsbgym-flex.txt
#RUN python3 -m pip install -r ./requirements_deep-glide.txt
RUN git clone https://github.com/afaehnrich/deep-glide.git
#RUN python3 train.py --algo sac --env JSBSim-v0 -n 1000 --eval-freq 1000 --save-freq 50000 --tensorboard-log logs
RUN ls /root -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
